version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - dupl
    - noinlineerr
    - funlen
    - gochecknoglobals
    - lll
    - revive
    - varnamelen
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        main:
          files:
            - '!$test'
          allow:
            - $gostd
            - github.com/greencoda
            - github.com/goccy/go-yaml
            - github.com/hashicorp/go-envparse
            - github.com/pelletier/go-toml
            - github.com/davecgh/go-spew/spew
    exhaustive:
      ignore-enum-members: reflect.+
    gosec:
      excludes:
        - G404
    interfacebloat:
      max: 20
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - segment
    paralleltest:
      ignore-missing: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - asasalint
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
